{% set version = "0.8.1" %}

package:
  name: macfsevents
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/M/MacFSEvents/MacFSEvents-{{ version }}.tar.gz
  sha256: 1324b66b356051de662ba87d84f73ada062acd42b047ed1246e60a449f833e10

build:
  number: 1002
  skip: True  # [not osx]
  script: {{ PYTHON }} -m pip install --ignore-installed --no-deps .

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - fsevents
  source_files:
    - tests.py
  requires:
    - pip
    - pytest-cov
  commands:
    - pip check
    - pytest tests.py -vv --cov=fsevents --no-cov-on-fail --cov-report=term-missing:skip-covered --cov-fail-under=100

about:
  home: https://github.com/malthe/macfsevents
  license: BSD-2-Clause
  license_family: BSD
  summary: Thread-based interface to file system observation primitives.
  description: |
    MacFSEvents is a Python library that provides thread-safe directory
    observation primitives using callbacks. It wraps the Mac OS X FSEvents
    API in a C-extension.

extra:
  recipe-maintainers:
    - pbronez
    - bollwyvl
